{{- if .Values.moodle.autoscaling.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Release.Name }}-web-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Release.Name }}-web
  minReplicas: {{ .Values.moodle.autoscaling.minReplicas }}
  maxReplicas: {{ .Values.moodle.autoscaling.maxReplicas }}
  metrics:
  {{- if .Values.moodle.autoscaling.targetCPUUtilizationPercentage }}
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: {{ .Values.moodle.autoscaling.targetCPUUtilizationPercentage }}
  {{- end }}
  {{- if .Values.moodle.autoscaling.targetMemoryUtilizationPercentage }}
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: {{ .Values.moodle.autoscaling.targetMemoryUtilizationPercentage }}
  {{- end }}
{{- end }}
