{{- if .Values.redis.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: moodle
      component: redis
  template:
    metadata:
      labels:
        app: moodle
        component: redis
    spec:
      containers:
      - name: redis
        image: "{{ .Values.redis.image }}"
        ports:
        - containerPort: 6379
        volumeMounts:
        - name: redis-data
          mountPath: /data
      volumes:
      - name: redis-data
        persistentVolumeClaim:
          claimName: {{ .Release.Name }}-redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-redis
spec:
  selector:
    app: moodle
    component: redis
  ports:
    - protocol: TCP
      port: 6379
      targetPort: 6379
{{- end }}
